# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dad-joker-2001
  namespace: "#{Kubernetes.Namespace}"
  labels:
    app: dad-joker-2001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dad-joker-2001
  template:
    metadata:
      labels:
        app: dad-joker-2001
    spec:
      containers:
        - name: dad-joker-2001
          image: teamdevextesting.azurecr.io/octopusdeploytesting/dad-joker-2001:#{Octopus.Action.Package[ephemeral-environments-demo].PackageVersion}
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
