apiVersion: v1
kind: Service
metadata:
  name: dad-joker-2001-service
  namespace: "#{Kubernetes.Namespace}"
spec:
  type: LoadBalancer
  selector:
    app: dad-joker-2001
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
