apiVersion: v1
kind: Service
metadata:
  name: dad-joker-2000-service
  namespace: "#{Kubernetes.Namespace}"
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "#{Kubernetes.Namespace}"
spec:
  type: LoadBalancer
  selector:
    app: dad-joker-2000
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
