apiVersion: v1
kind: Service
metadata:
  name: ephemeral-environments-demo-service
  namespace: "#{Kubernetes.Namespace}"
spec:
  type: LoadBalancer
  selector:
    app: ephemeral-environments-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
