name: Build docker image and release with Octopus

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  REGISTRY_NAME: ${{ secrets.CONTAINER_REGISTRY_NAME }}
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY_URL }}
  IMAGE_NAME: OctopusDeployTesting/dad-joker-2000
  OCTOPUS_SPACE: Demo

jobs:
  test_environment:
    name: Deploy to test environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}

      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@0340291411457e779fd51e65b1fd804c5dccb3b9
        with:
          version: '*'
          
      - name: list-octopusdeploy-accounts
        env:
          OCTOPUS_SPACE: 'Demo'
        run: >
          octopus account list
