name: Build docker image and release with Octopus

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  REGISTRY_NAME: ${{ secrets.CONTAINER_REGISTRY_NAME }}
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY_URL }}
  IMAGE_NAME: OctopusDeployTesting/dad-joker-2000
  OCTOPUS_SPACE: Demo

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Get release version
        id: get_release_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"

      - name: test Get branch names
        id: branch_names
        uses: OctopusDeploy/util-actions/current-branch-name@cat/125029/update-node-in-packages
      - name: Print branch names output
        run: |
          echo "Branch Name: ${{ steps.branch_names.outputs.branch_name }}"
      
      - name: Test add-changeset
        uses: OctopusDeploy/util-actions/add-changeset@cat/125029/update-node-in-packages
        with:
          type: patch
          summary: Test changeset for manual testing
          ignore: |
            node_modules/**
            **/__tests__/**

      - name: Test add-changeset
        id: add_changeset
        uses: OctopusDeploy/util-actions/add-changeset@cat/125029/update-node-in-packages
        with:
          type: patch
          summary: Test changeset for manual testing
          ignore: |
            node_modules/**
            **/__tests__/**
      - name: Print add-changeset outputs
        run: |
          echo "Changeset Name: ${{ steps.add_changeset.outputs.changesetName }}"
          echo "Changeset Path: ${{ steps.add_changeset.outputs.changesetPath }}"
      
      - name: Test find-and-replace-all (string)
        id: find_replace_string
        uses: OctopusDeploy/util-actions/find-and-replace-all@cat/125029/update-node-in-packages
        with:
          source: The quick brown fox jumps over the lazy dog
          searchString: the
          replace: hooray
      - name: Print find-and-replace-all (string) output
        run: | 
          echo "Result: ${{ steps.find_replace_string.outputs.value }}"
        
      - name: Test find-and-replace-all (regex)
        id: find_replace_regex
        uses: OctopusDeploy/util-actions/find-and-replace-all@cat/125029/update-node-in-packages
        with:
          source: The quick brown fox jumps over the lazy dog
          searchRegex: the
          searchRegexFlags: i
          replace: hooray
      - name: Print find-and-replace-all (regex) output
        run: |
          echo "Result: ${{ steps.find_replace_regex.outputs.value }}"

      - name: Test extract-package-details
        id: extract_package
        uses: OctopusDeploy/util-actions/extract-package-details@cat/125029/update-node-in-packages
        with:
          path: ./app/  # Or path to a directory containing package.json in your repo
      - name: Print extract-package-details outputs
        run: |
          echo "Package Name: ${{ steps.extract_package.outputs.name }}"
          echo "Package Version: ${{ steps.extract_package.outputs.version }}"