name: Deprovision Ephemeral Environment

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deprovision:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}

      - name: 🐙 Deprovision Ephemeral Environment Action
        uses: OctopusDeploy/deprovision-ephemeral-environment@main # update to @v1 once released
        with:
          # Use PR number if it exists, otherwise use branch name
          name: ${{ github.event.pull_request.number && format('pr-{0}', github.event.pull_request.number) || format('branch-{0}', github.ref_name) }}
          space: "Demo"
          project: "Dad Joker 2000"
